apiVersion: v1
kind: Service
metadata:
  name: {{ include "tomcat-app.fullname" . }}
  labels:
    app: {{ include "tomcat-app.name" . }}
    profile: {{ .Values.profile }}
spec:
  type: NodePort
  selector:
    app: {{ include "tomcat-app.name" . }}
    profile: {{ .Values.profile }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 8443
      targetPort: 8443
      protocol: TCP